import './globals.css';
import type { Metadata } from 'next';
import { Fragment_Mono } from 'next/font/google';
import { ThemeProvider } from '@/components/ui/theme-provider';
const fragMono = Fragment_Mono({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={fragMono.className}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
